### ISSUE TITLE
Clarification needed on use of "file"

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DRM#17]
DRM related text often uses the term "file", it should be clarified what this term means: a DASH Segment (in general) or specifically a media/init Segment.

Specifically, the beginning statement of Section 7.7.6 is quite ambiguous:

"Periods SHALL only change default_KID and corresponding license at the start of a new Period corresponding to a different file."

Here use of "Period" as a subject is confusing. Probably what is intended to be said is: default_KID in the 'tenc' box of the initalization segment may change at the start of a new Period ...?

**Comment by lpiron** [comment]
Following Content Security call, the proposal is to change this sentence to
"If a new license is needed and default_KID is to be changed, it SHALL be at the beginning of a Period"

**Comment by haudiobe** [comment]
addressed in v4.02
