### ISSUE TITLE
“root” and “leaf” license 

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DRM#5]
Does the concept of “root” and “leaf” license apply to all DRM schemes or do some schemes achieve key rotation through out-of-band means? The doc talks about combing leaf and root, but can you elaborate on how?

**Comment by nthorwir** [comment]
see my earlier comment: 
"
I don't think that any of the standards mandates, recommends or even mentions the root/leaf concept. I believe it is OK to provide some clarification on how it can be used, but should it not be too specific. 
"

**Comment by haudiobe** [comment]
Conclusion: Root and leaf license concept is DRM specific and so are ways of combining them. I don’t have any more questions here.

**Comment by haudiobe** [comment]
In 1.4.1: Add clarification: 
- The presence of "root" and "leaf" licenses is DRM specific and also the combination is DRM specific.
  Niels integrates!

**Comment by nthorwir** [comment]
clarified as: 

This may be used to download a Root license bound to this device, necessary to read the key rotation Segment licenses common to all Media Segments in the case where the DRM is using a root and leaf license hierarchy.
Note that the presence and use of root and leaf licenses is optional and DRM spe-cific.

**Comment by andrejp** [comment]
Clarification is ok.
