### ISSUE TITLE
root license info delivery

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DRM#7]
When root and leaf licenses are used for key rotation, do you see root license info delivered in-band and/or MPD? How about leaf – only in-band?

**Comment by andrejp** [comment]
The leaf license (not information) is in-band. Root 'info' depends on implementation could be MPD or some other way. Client might now how to get root license. DRM specific

**Comment by nthorwir** [comment]
Agree that this is DRM specific. I don't think that any of the standards mandates, recommends or even mentions the root/leaf concept. I believe it is OK to provide some clarification on how it can be used, but should it not be too specific.

**Comment by andrejp** [comment]
Shouldn't be too specific there might be DRM systems who doesn't use Root / Leaf at all. It's good to have some general description

**Comment by haudiobe** [comment]
Conclusion:

Leaf license is delivered only in-band. Root delivery is DRM specific – can be in-band, MPD, out-of-band. I don’t have any more questions here.

**Comment by haudiobe** [comment]
Add clarification: "Delivery of root and leaf licenses is also DRM specific. Typically leaf license is delivered in-band (maybe provide reason real-time, etc.), but not necessarily the case." Niels adds clarification.

**Comment by nthorwir** [comment]
added in 1.4.1 
In the case of key rotation, if root licenses are used, the same requirement applies to the root li-censes (one per DRM), and also means all Representations shall have the same value of ‘de-fault_KID’ in their ‘tenc’ boxes in their Initialization Segments. The use of root and leaf licenses is optional and DRM specific, but lead licenses are typically delivered in band to allow real time  license acquisition.

**Comment by andrejp** [comment]
I agreed to the clarification.
